#!/bin/bash
# run this file from the repository root
set -ex

export DOCKER_BUILDKIT=1

docker build \
    --progress=plain \
    --tag pynvml:${CHANGE_BRANCH}_${BUILD_NUMBER} \
    --file ci/Dockerfile .

docker run \
    --interactive \
    --tty \
    --name pynvml \
    --gpus all pynvml:${CHANGE_BRANCH}_${BUILD_NUMBER}

docker cp pynvml:/sandbox/artifacts .
docker container rm pynvml
docker image rm pynvml:${CHANGE_BRANCH}_${BUILD_NUMBER}
