pipeline {
    agent { label "docker-gpu"}
    environment {
        DOCKER_BUILDKIT=1
        UBUNTU_BASE_TAG=20.04
    }
    stages {
        stage("Capture Build Info"){
            steps {
                rtBuildInfo (captureEnv: true)
            }
        }
        stage("Build Docker image with wheels") {
            steps {
                sh script: """
                    docker build \
                        --progress=plain \
                        --tag pynvml:${BUILD_NUMBER} \
                        --file ci/Dockerfile .
                    """
            }
        }
        stage("Test"){
            steps {
                sh script: """
                    docker run \
                        --interactive \
                        --name pynvml \
                        --gpus all pynvml:${BUILD_NUMBER}
                    """
                sh script: "docker cp pynvml:/sandbox/artifact ."
                sh script: "docker container rm pynvml"
                sh script: "docker image rm pynvml:${BUILD_NUMBER}"
            }
        }
        stage("Upload artifacts") {
            steps {
                sh script: "echo Not implemented"
            }
        }
    }
}