pipeline {
    agent none
    stages {
        stage("pynvml") {
            agent {
                dockerfile {
                    filename 'Dockerfile'
                    dir './ci'
                    label 'docker-gpu'
                    additionalBuildArgs  '--network host'
                    args '-v /dev/log:/dev/log --gpus all --network host'                }
            }
            steps {
                rtBuildInfo (captureEnv: true)
                sh script: 'tox -p'
            }
            post {
                always {
                    archiveArtifacts artifacts: 'artifacts/*'
                    junit testResults: 'artifacts/xunit-*.xml'
                }
                success {
                    rtUpload (
                        failNoOp: true,
                        serverId: 'uspa-arty',
                        spec: """{
                            "files": [{
                                "pattern": "artifacts/pynvml-*.whl",
                                "target": "m3d-playground"
                            }]
                        }""",
                    )
                    rtPublishBuildInfo(serverId: 'uspa-arty')
                }
            }
        }
    }
}
